export const FETCHING_COIN_DATA = "FETCHING_COIN_DATA";
export const FETCHING_COIN_DATA_SUCCESS = "FETCHING_COIN_DATA_SUCCESS";
export const FETCHING_COIN_DATA_FAIL = "FETCHING_COIN_DATA_FAIL";
export const FETCHING_COIN_NEWS = "FETCHING_COIN_NEWS"
export const FETCHING_COIN_NEWS_SUCCESS = "FETCHING_COIN_NEWS_SUCCESS"
export const FETCHING_COIN_NEWS_FAIL = "FETCHING_COIN_NEWS_FAIL"